include: ["documentation/mElite-html/_test.html", "documentation/mElite-html/_star_8h.html", "documentation/_test.html", "_test.html"]

exclude: ["documentation/mElite-html/test.html", "documentation/test.html", "test.html"]